spring:
  data:
    redis:
      port: 6379         # Redis 服务器连接端口
      host: 127.0.0.1    # Redis 服务器地址
      database: 0        # Redis 数据库索引（默认为0）
      password:          # Redis 服务器连接密码（默认为空）
      lettuce:
        pool:
          min-idle: 10    # 连接池中的最小空闲连接 默认0
          max-idle: 20    # 连接池中的最大空闲连接 默认0
          max-active: 100 # 连接池最大连接数（使用负值表示没有显示） 默认0