#logging:
#  level:
##    root 表示全局日志级别，INFO 表示将显示信息级别及其以上（包括WARN、ERROR）
##    如果需要更详细的日志，可以将日志级别调为DEBUG，这样可以查看每个操作的详细信息。
#    root: info
##    com.example.demo 是包的路径，DEBUG 级别将显示详细的调试信息
#    com.example.demo: debug

#spring:
#  devtools:
#    remote:
#      enabled: true    # 启动远程调试
#      secret: mysecret # 设置远程连接的密钥，用于安全验证
#      restart:
#        enabled: true  # 启用远程重启功能

## 这样设置后，每次修改完代码，不管手动编译还是自动编译，都无法热更新，必须直接重启。
#spring:
#  devtools:
#    restart:
#      enabled: false # 禁用自动重启
#    livereload:
#      enabled: false # 禁用 LiveReload

## 监听文件的更改
#spring:
#  devtools:
#    restart:
#      additional-paths:
#        - src/main/resources/config # 监听 config 目录下的文件变化

#spring:
#  profiles:
#    active: dev
#
#    devtools:
#      restart:
#        enabled: true          # 启用自动重启
#        exclude:               # 排除不处罚重启的路径
#          - static/**
#          - public/**
#        additional-paths:      # 监控额外路径
#          - src/main/resources/config
#        additional-exclude:
#          - src/main/resources/**/*.md            # 排除 Markdown 文件的变更
#      livereload:
#        enabled: true          # 启用 LiveReload
#        port: 35729            # 设置 LiveReload 的端口号
#
#remote:
#        enabled: false         # 禁用远程调试
#        secret: mysecret       # 如果启用远程调试，请设置安全密钥
#
#thymeleaf:
#  cache: false                 # 禁用 Thymeleaf 缓存
#
#mvc:
#  cache-period: 0              # 禁用静态资源缓存
#  log-resolved-exception: true # 启用异常日志

spring:
  thymeleaf:
    cache: false # 禁用 Thymeleaf 缓存，以确保每次请求都加载最新的模板文件