#logging:
#  level:
##    root 表示全局日志级别，INFO 表示将显示信息级别及其以上（包括WARN、ERROR）
##    如果需要更详细的日志，可以将日志级别调为DEBUG，这样可以查看每个操作的详细信息。
#    root: info
##    com.example.demo 是包的路径，DEBUG 级别将显示详细的调试信息
#    com.example.demo: debug