family:
  family-name: "happy family"
  father: "Jack"
  mother: "Rose"
  child: "Tom"
  age: ${random.int(5,10)}

person:
  first-name: "${first.name:John}"
  last-name: "${last.name:Doe}"
  age: "${random.int(20,50)}"
  id: "${random.uuid}"
  phone: "${phone.number:1234567890}"

first:
  name: miao
last:
  name: xinyu