#family:
#  family-name: "happy family"
#  father: "Jack"
#  mother: "Rose"
#  child: "Tom"
#  age: ${random.int(5,10)}

person:
  first-name: "${first.name:John}"
  last-name: "${last.name:Doe}"
  age: "${random.int(20,50)}"
  id: "${random.uuid}"
  phone: "${phone.number:1234567890}"

first:
  name: miao
last:
  name: xinyu

student:
  name: 张小飞
  age: 20
  happy: true
  birth: 2004/01/01
  map: {k1: v1,k2: v2}
  list:
    - code
    - read
    - music
  dog:
    name: 虎子
    age: 11