# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:6033/spring_boot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 1286280961@qq.com
    password: dnnqkcjdyoobbaac
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  quartz:
    job-store-type: JDBC # 数据库存储 quartz 任务配置
    jdbc:
      initialize-schema: NEVER # 自动初始化表结构，第一次启动的时候这里写 always

# 配置 MP 框架日志级别
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

# MP 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: top.xym.springboot.task.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl